Feature rhino turn with encoder
R2D2-2019/moving_platform pull request #22
Opened 2019-06-19 21:33 UTC by crisvdn

This pull request implements a working rhino class. This rhino class can turn with the encoders and drive forward/ backwards.

2019-06-20 09:09 UTC, Joepieler requested changes

2019-06-20 09:09 UTC, Joepieler commented on code/main.cpp
> -    auto beetle =
a qik can't be a beetle and a rhino at the same time

2019-06-20 09:09 UTC, Joepieler commented on code/main.cpp
> +    if (rhino_motor_test) {
No tests in the main of the release.

2019-06-20 09:09 UTC, Joepieler commented on code/src/rhino.cpp
> +        unsigned int adc_voltage = 3500;
adc_voltage can be constexpr

2019-06-20 09:09 UTC, Joepieler commented on code/src/rhino.cpp
> +                (int(encode_1_full_turn * turn_factor / 360 * degrees))) {
can be calculated before the loop

2019-06-20 09:09 UTC, Joepieler commented on code/src/rhino.cpp
> +        while (true && degrees != 0) {
the True can go away.

2019-06-24 19:43 UTC, crisvdn commented on code/src/rhino.cpp
> +        while (true && degrees != 0) {
This has been changed.

2019-06-24 19:43 UTC, crisvdn commented on code/src/rhino.cpp
> +                (int(encode_1_full_turn * turn_factor / 360 * degrees))) {
This calculation is now stored in a variable.

2019-06-24 19:43 UTC, crisvdn commented on code/src/rhino.cpp
> +        unsigned int adc_voltage = 3500;
This variable is now constexpr static.

2019-06-24 19:43 UTC, crisvdn commented on code/main.cpp
> +    if (rhino_motor_test) {
Fixed.

2019-06-24 19:44 UTC, crisvdn commented on code/main.cpp
> -    auto beetle =
Fixed.

2019-06-24 20:03 UTC, Joepieler approved these changes
Everything i asked for has been changed.

2019-06-24 20:04 UTC, merged